[build]
command = "npx vite build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/transparency"
to = "/transparency/index.html"
status = 200

[[redirects]]
from = "/transparency/*"
to = "/transparency/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
framework = "vite"
targetPort = 5173
