[build]
command = "npx vite build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/transparency"
to = "https://li-vela-transparency-dashboard-ng6c7ig76a-ue.a.run.app/transparency"
status = 200
force = true

[[redirects]]
from = "/transparency/*"
to = "https://li-vela-transparency-dashboard-ng6c7ig76a-ue.a.run.app/transparency/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
framework = "vite"
targetPort = 5173
